# sample1 - テンソル基礎

PyTorch の基本データ構造である **テンソル（Tensor）** を学びます。
NumPy の ndarray に似ていますが、GPU で演算できる点が大きな違いです。

| ステップ | 内容 |
|----------|------|
| 1 | テンソルの作成 |
| 2 | テンソルの属性 |
| 3 | 基本演算 |
| 4 | 形状変換 |
| 5 | NumPy との相互変換 |

## 1. テンソルの作成

In [1]:
import torch
import numpy as np

# 直接値を指定
t1 = torch.tensor([1.0, 2.0, 3.0])
print("1次元テンソル:", t1)

# 2次元テンソル（行列）
t2 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("2次元テンソル:\n", t2)

# ゼロ・1・乱数
print("zeros:", torch.zeros(2, 3))
print("ones :", torch.ones(2, 3))
print("rand :", torch.rand(2, 3))   # 0〜1 の一様乱数
print("randn:", torch.randn(2, 3))  # 標準正規分布

1次元テンソル: tensor([1., 2., 3.])
2次元テンソル:
 tensor([[1, 2, 3],
        [4, 5, 6]])
zeros: tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones : tensor([[1., 1., 1.],
        [1., 1., 1.]])
rand : tensor([[0.6392, 0.9508, 0.5829],
        [0.1231, 0.2729, 0.2678]])
randn: tensor([[ 1.4392,  0.0450,  2.1146],
        [-0.5804,  1.5254,  0.5216]])


## 2. テンソルの属性

In [2]:
t = torch.randn(3, 4)
print("shape  :", t.shape)    # 形状
print("dtype  :", t.dtype)    # データ型
print("device :", t.device)   # CPU / GPU
print("ndim   :", t.ndim)     # 次元数
print("numel  :", t.numel())  # 要素数

shape  : torch.Size([3, 4])
dtype  : torch.float32
device : cpu
ndim   : 2
numel  : 12


## 3. 基本演算

In [3]:
a = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
b = torch.tensor([[5.0, 6.0], [7.0, 8.0]])

print("加算  :\n", a + b)
print("要素積:\n", a * b)          # アダマール積
print("行列積:\n", torch.mm(a, b)) # 行列の掛け算
print("合計  :", a.sum())
print("平均  :", a.mean())
print("最大  :", a.max())

加算  :
 tensor([[ 6.,  8.],
        [10., 12.]])
要素積:
 tensor([[ 5., 12.],
        [21., 32.]])
行列積:
 tensor([[19., 22.],
        [43., 50.]])
合計  : tensor(10.)
平均  : tensor(2.5000)
最大  : tensor(4.)


## 4. 形状変換

In [4]:
t = torch.arange(12)  # 0〜11 の1次元テンソル
print("元の形状:", t.shape, "->", t)

# reshape: 形状変換
t2 = t.reshape(3, 4)
print("reshape(3,4):\n", t2)

# view: reshape と似ているがメモリ連続が必要
t3 = t.view(2, 6)
print("view(2,6):\n", t3)

# squeeze / unsqueeze: 次元の削除・追加
t4 = torch.tensor([1.0, 2.0, 3.0])
print("unsqueeze(0):", t4.unsqueeze(0).shape)  # (1, 3)
print("unsqueeze(1):", t4.unsqueeze(1).shape)  # (3, 1)

元の形状: torch.Size([12]) -> tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
reshape(3,4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
view(2,6):
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
unsqueeze(0): torch.Size([1, 3])
unsqueeze(1): torch.Size([3, 1])


## 5. NumPy との相互変換

In [5]:
# NumPy → Tensor
arr = np.array([1.0, 2.0, 3.0])
t = torch.from_numpy(arr)
print("NumPy → Tensor:", t, type(t))

# Tensor → NumPy
arr2 = t.numpy()
print("Tensor → NumPy:", arr2, type(arr2))

# 注意: メモリを共有しているので片方を変えると両方変わる
t[0] = 99
print("Tensor 変更後の NumPy:", arr2)  # arr2 も変わる

NumPy → Tensor: tensor([1., 2., 3.], dtype=torch.float64) <class 'torch.Tensor'>
Tensor → NumPy: [1. 2. 3.] <class 'numpy.ndarray'>
Tensor 変更後の NumPy: [99.  2.  3.]
